### ISSUE TITLE
Must specify an AWS region

### ISSUE THREAD

**Issue by apmorton** [mattgodbolt/compiler-explorer-image#209]
```$ bin/ce_install --help
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amorton/compiler-explorer-image/bin/lib/ce_install.py", line 11, in <module>
    from lib.installation import InstallationContext, installers_for
  File "/home/amorton/compiler-explorer-image/bin/lib/installation.py", line 14, in <module>
    from lib.amazon import list_compilers
  File "/home/amorton/compiler-explorer-image/bin/lib/amazon.py", line 4, in <module>
    ec2 = boto3.resource('ec2')
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/args.py", line 117, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/amorton/compiler-explorer-image/.env/lib/python3.6/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

https://stackoverflow.com/questions/40377662/boto3-client-noregionerror-you-must-specify-a-region-error-only-sometimes

Would be nice if the scripts detected lack of region config and set some default so that at least read-only aws operations can continue.

```diff
diff --git a/bin/lib/amazon.py b/bin/lib/amazon.py
index 144332b..e459b72 100644
--- a/bin/lib/amazon.py
+++ b/bin/lib/amazon.py
@@ -1,6 +1,10 @@
 import boto3
 from operator import attrgetter

+# set default region if the user doesn't have any aws configuration
+if not boto3.session.Session().region_name:
+    boto3.setup_default_session(region_name='us-west-2')
+
 ec2 = boto3.resource('ec2')
 s3 = boto3.resource('s3')
 as_client = boto3.client('autoscaling')

```

**Comment by mattgodbolt** [comment]
Good idea; thanks
