### ISSUE TITLE
Unable to update compilers

### ISSUE THREAD

**Issue by brycelelbach** [mattgodbolt/compiler-explorer-image#249]
Following the instructions in README.md:

```
[13:49:15]:root@voyager:/home/wash/development/nvidia/compiler_explorer_image:0:# ./update_compilers/install_compilers.sh 
++ set -o pipefail
++ mkdir -p /opt/compiler-explorer
++ cd /opt/compiler-explorer
++ ARG1=
++ PATCHELF=/opt/compiler-explorer/patchelf-0.8/src/patchelf
++ S3BUCKET=compiler-explorer
++ SUBDIR=opt
++ S3URL=https://s3.amazonaws.com/compiler-explorer/opt
+++ /home/wash/development/nvidia/compiler_explorer_image/update_compilers/../bin/list_compilers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wash/development/nvidia/compiler_explorer_image/bin/lib/list_compilers.py", line 7, in main
    print(" ".join(list_compilers(with_extension=True)))
  File "/home/wash/development/nvidia/compiler_explorer_image/bin/lib/amazon.py", line 248, in list_compilers
    for page in s3_paginator.paginate(Bucket='compiler-explorer', Prefix=prefix):
  File "/usr/local/lib/python3.7/dist-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/dist-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/dist-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/dist-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/dist-packages/botocore/auth.py", line 425, in add_auth
    super(S3SigV4Auth, self).add_auth(request)
  File "/usr/local/lib/python3.7/dist-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
++ ALL_COMPILERS=
```

This was only after I hacked up .env/pyvenv.cfg to include system packages, because otherwise I got an error when `boto3` was being imported.

This used to work for me a few months ago.

**Comment by apmorton** [comment]
@brycelelbach this should be fixed in 9aa341186dfba6c7cb7753431a6f88d94eae4d57 - can you confirm?

Not sure about the import issues you had with boto3 - I haven't had any problems on that front.

**Comment by partouf** [comment]
I always comment out this line https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/common.inc#L46
will test if this commit fixes it as well

**Comment by apmorton** [comment]
Yeah - that is the line that caused the issue.

Commenting it only breaks nightly installs, so if you didn't care about those it is a valid fix.

**Comment by partouf** [comment]
I just assume nightlies are broken by default and we'll get comments about it always (though we rarely do, but we do every once in a while) ;) I only test fixed version

**Comment by partouf** [comment]
I now got the error that I had to "make ce", I did successfully, and was able to run the script without issues (well, my disk is full, so there are errors about that, but that's normal)
