### ISSUE TITLE
Can't list compilers on remote site

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer-image#40]
Permissions on s3 are broken again:

```
+ S3URL=https://s3.amazonaws.com/compiler-explorer/opt
++ python //list_compilers.py --s3url https://s3.amazonaws.com/compiler-explorer --prefix opt/
Traceback (most recent call last):
  File "//list_compilers.py", line 21, in <module>
    sys.exit(main(parser.parse_args()))
  File "//list_compilers.py", line 10, in main
    result = urlopen(args.s3url + "?prefix=" + args.prefix).read()
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by mattgodbolt** [comment]
Fixed now. I hope. The downside is that anyone can list all the objects in the `compiler-explorer` bucket, but I don't think that's a problem as there's nothing sensitive there in the names...only the contents (and that only of logs and non-free compiler licenses etc)
