### ISSUE TITLE
build_compiler.py failure

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer-image#81]
```
-- Installing: /root/staging/lib/cmake/llvm/./TableGen.cmake
-- Installing: /root/staging/lib/cmake/llvm/./GetSVN.cmake
-- Installing: /root/staging/lib/cmake/llvm/./HandleLLVMOptions.cmake
-- Installing: /root/staging/lib/cmake/llvm/./DetermineGCCCompatible.cmake
-- Installing: /root/staging/lib/cmake/llvm/./HandleLLVMStdlib.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CheckAtomic.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CheckLinkerFlag.cmake
-- Installing: /root/staging/lib/cmake/llvm/./AddSphinxTarget.cmake
-- Installing: /root/staging/lib/cmake/llvm/./GenerateVersionFromCVS.cmake
ERROR: /root/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
2018-06-04 09:50:24.434889 : Command returned exit code 78
2018-06-04 09:50:24.434953 : Shutting down instance
2018-06-04 09:50:26.254858 : Command returned exit code -1
2018-06-04 09:50:36.262643 : NOT terminating instance as build failed. Stopping instead
Traceback (most recent call last):
  File "./build_compiler.py", line 165, in <module>
    instance.stop()
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnsupportedOperation) when calling the StopInstances operation: The instance 'i-07f6222c1325d835b' is a spot instance and may not be stopped.
```

**Comment by mattgodbolt** [comment]
command line was: `./build_compiler.py clang trunk s3://gcc-explorer/opt/ --spot-price 0.8 -t c4.4xlarge --key-file ~/ec2-mattgodbolt.pem`

**Comment by mattgodbolt** [comment]
Fixed (sort of); build_compiler deprecated now we have a build instance.
